{
 "title": "Podman Exporter Dashboard",
 "description": "This dashboard leverages Prometheus podman exporter as the data source and utilizes various visualization panels like time series and tables, providing critical insights into the operational metrics of Podman containers.",
 "tags": [
  "podman",
  "prometheus-podman-exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values(podman_container_info{instance=~\"$instance\"},instance)"
    }
   },
   {
    "name": "name",
    "label": "Container",
    "query": {
     "query": "label_values(podman_container_info{name=~\"$name\", instance=~\"$instance\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (podman_container_info{instance=~'$instance', name=~\"$name\"} * on(id) group_right (name) rate(podman_container_cpu_seconds_total[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (\n    podman_container_info{instance=~\"$instance\", name=~\"$name\"}\n  * on (id) group_right (name)\n    (podman_container_mem_usage_bytes / 1024 / 1024)\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Recieved Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(name) (podman_container_info{instance=~\"$instance\", name=~\"$name\"} * on(id) group_right(name) rate(podman_container_net_input_total[1m]) / 1024)",
     "legendFormat": "{{name}} - Read"
    },
    {
     "expr": "sum(rate(podman_container_blkio_device_write_bytes_total{instance=~\"$host\",name=~\"$container\"}[5m])) by (name)",
     "legendFormat": "{{name}} - Write"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(name) (podman_container_info{instance=~\"$instance\", name=~\"$name\"} * on(id) group_right(name) rate(podman_container_net_output_total[1m]) / 1024)",
     "legendFormat": "{{name}} - Read"
    },
    {
     "expr": "sum(rate(podman_container_blkio_device_write_bytes_total{instance=~\"$host\",name=~\"$container\"}[5m])) by (name)",
     "legendFormat": "{{name}} - Write"
    }
   ]
  },
  {
   "title": "Container Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "podman_container_info{instance=~\"$instance\", name=~\"$name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=~\"$instance\", name=~\"$name\"} * on (id) group_right (name) (podman_container_state))",
     "legendFormat": "状态"
    },
    {
     "expr": "(podman_container_info{instance=~\"$instance\", name=~\"$name\"} * on (id) group_right (name) (podman_container_mem_usage_bytes))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=~\"$instance\", name=~\"$name\"} * on (id) group_right (name) (podman_container_exit_code))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=~\"$instance\", name=~\"$name\"} * on (id) group_right (name) (time() - podman_container_started_seconds))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=~\"$instance\", name=~\"$name\"} * on (id) group_right (name) (podman_container_pids))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=~\"$instance\", name=~\"$name\"} * on (id) group_right (name) (podman_container_mem_usage_bytes / (podman_container_mem_limit_bytes)))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}