[metadata]
name = "start-code"
description = "A channel to quickly jump into or start a new coding session"
requirements = ["find"]

[source]
command = ["find $HOME/code $HOME/.config $HOME/worktrees -mindepth 1 -maxdepth 1 -type d"]

[preview]
command = "ls -la --color=always '{}'"

# [actions.zellij]
# description = "Opens a new zellij session in the directory"
# command = "zellij-session {}"
# mode = "execute"
#
# [actions.tmux]
# description = "Opens a tmux session in the directory"
# command = "tmux-sessionizer {}"
# mode = "execute"
#
# [keybindings]
# enter = "actions:tmux"
