---
zfs_datasets:
  - name: main
  - name: main/audiobookshelf
  - name: main/copyparty
  - name: main/data
  - name: main/deadfire
  - name: main/forgejo
  - name: main/immich
  - name: main/jellyfin
  - name: main/pinchflat

nas_directories:
  - path: /main/copyparty/hists
    owner: "1000"
    group: "1000"
    mode: "0775"
  - path: /main/copyparty/data
    owner: "1000"
    group: "1000"
    mode: "0775"
  - path: /main/jellyfin/config
    owner: "1000"
    group: "1000"
    mode: "0775"
  - path: /main/jellyfin/media
    owner: "1000"
    group: "1000"
    mode: "0775"
  - path: /main/jellyfin/media/pinchflat
    owner: "1000"
    group: "1000"
    mode: "0775"
  - path: /main/pinchflat/config
    owner: "1000"
    group: "1000"
    mode: "0775"

nfs_exports:
  - path: /main
    clients:
      - host: "*"
        options: rw,sync,fsid=0,crossmnt,no_subtree_check
  - path: /main/jellyfin
    clients:
      - host: "*"
        options: rw,sync,no_subtree_check
  - path: /main/immich
    clients:
      - host: "*"
        options: rw,sync,no_subtree_check,no_root_squash
  - path: /main/forgejo
    clients:
      - host: "*"
        options: rw,sync,no_subtree_check,no_root_squash
  - path: /main/audiobookshelf
    clients:
      - host: "*"
        options: rw,sync,no_subtree_check,no_root_squash
