#!/usr/bin/env bash
directory=$1
session_name=$2

cd $directory

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $session_name
    exit 0
fi

if ! tmux has-session -t=$session_name 2> /dev/null; then
    tmux new-session -ds $session_name
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t $session_name
else
    tmux switch-client -t $session_name
fi
