#!/usr/bin/env bash
directory=$1
echo $directory

base_name=$(basename "$directory")
parent_path=$(dirname "$directory")
parent_name=$(basename "$parent_path")
session_name="${parent_name}_${base_name}"
echo $session_name

cd $directory

tmux new-session -ds $session_name

_tmux_switch_or_attach $session_name
