#! /usr/bin/env bash

selected=$(find ~/code -mindepth 1 -maxdepth 1 -type d | fzf)

cd $selected

is_worktree=$(git rev-parse --is-inside-work-tree)

if [[ "$is_worktree" == "false" ]]; then
    selected=$(find $selected -mindepth 1 -maxdepth 1 -type d | fzf)
fi

echo $selected
