#!/usr/bin/env bash

directory=$(findcode)

if [[ -z $directory ]]; then
    exit 0
fi

session_name="$(basename "$directory")"

if zellij list-sessions 2>/dev/null | awk '{print $1}' | grep -q "$session_name"; then
    zellij attach "$session_name"
else

cd $directory
