#!/bin/sh

# Script for use in waybar to display # of pacman updates
LOCKFILE=/tmp/pacman-updates.lock
if [ -e $LOCKFILE ]; then
	exit 0
fi

touch $LOCKFILE
trap "rm -f $LOCKFILE" EXIT

OUTPUT="$(checkupdates)"

if [ -z "$OUTPUT" ]; then
	echo "" >> /tmp/update.log
	exit 0
else
	NUMBER="$(echo "$OUTPUT" | wc -l)"
	echo "󰏔 $NUMBER updates" >> /tmp/update.log
	exit 0
fi
rm -rf $LOCKFILE

