#! /bin/sh

chosen=$(printf "Power Off\nRestart\nSleep\nCancel" | rofi -dmenu -i)

case "$chosen" in
    "Power Off") systemctl poweroff ;;
    "Restart") systemctl reboot ;;
    "Sleep") systemctl sleep ;;
    "Cancel") exit 0 ;;
    *) exit 1 ;;
esac
