#! bash
IP=$1  # replace with the slow v4 IP you observed
URL=$2

# At home network (no exit node):
curl -4 -L --resolve "cache.nixos.org:443:$IP" \
  -r 0-49999999 -o /dev/null --max-time 120 \
  -w "home ip=$IP ttfb=%{time_starttransfer} speed=%{speed_download}B/s\n" \
  "$URL"

