#!/usr/bin/env bash

directory=$1

if [[ -z $directory ]]; then
    exit 0
fi

cd $directory
session_name=$(basename $directory)

tmux new-session -ds $session_name

if [[ -z $TMUX ]]; then
    tmux attach-session -t $session_name
else
    tmux switch-client -t $session_name
fi

