#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/code -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

cd $selected

is_bare=$(git rev-parse --is-bare-repository)
echo $is_bare

if [ "$is_bare" == "true" ]; then
    selected=$(ls | fzf)
    cd $selected
fi

tmux_running=$(pgrep tmux)

session_name=$(basename $selected)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $session_name
    exit 0
fi

if ! tmux has-session -t=$session_name 2> /dev/null; then
    tmux new-session -ds $session_name
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t $session_name
else
    tmux switch-client -t $session_name
fi
