---
- name: Ensure required NAS directories are present
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('1000') }}"
    group: "{{ item.group | default('1000') }}"
    mode: "{{ item.mode | default('0775') }}"
    recurse: "{{ item.recurse | default(false) | bool }}"
  loop: "{{ nas_directories | default([]) }}"

- name: Ensure required NAS files are present
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: touch
    owner: "{{ item.owner | default('1000') }}"
    group: "{{ item.group | default('1000') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ nas_files | default([]) }}"
