set -g prefix C-Space
set -g mouse on

set -sg escape-time 0
set -g status-position top
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set-option -g exit-empty off

set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor"

bind-key -r f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"

# colors
# catppuccin mocha colors
set -g @base_text "#cdd6f4"
set -g @selected_text "#89b4fa"
set -g @unselected_text "#a6adc8"
set -g @background "#11111b"

# theme
set -g status-style "bg=#{@background}"
set -g status-right ""
set -g status-left "#[fg=#{@base_text}] #S "
set -g status-left-length 30

# prefix indicator - flash red when in leader mode
set -g status-left "#{?client_prefix,#[bg=red],}#[fg=#{@base_text}] #S #{?client_prefix,#[bg=#{@background}],}"
set -g window-status-current-style "fg=#{@selected_text}"
set -g window-status-style "fg=#{@unselected_text}"
set -g window-status-current-format "#I #W"
set -g window-status-format "#I #W"
set -g window-status-separator " | "

# reload config
bind r source-file ~/.tmux.conf
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind-key 'X' kill-session

# better split keys
unbind '"'
unbind %
bind-key - split-window -v
bind-key '\' split-window -h
bind-key 't' split-window -v -l '20%'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-sessionx'

set -g @sessionx-bind 's'

run '~/.tmux/plugins/tpm/tpm'
